<a href="https://colab.research.google.com/github/mitsu-hm/Google-Collab/blob/main/Lab1B10Vinayak_Dubey_590025396.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = {"Students_name":["A","B","C","D","E","F"],
           "Marks":[65,54,np.nan,66,np.nan,78],
           "Attendance":[90,np.nan,85,120,np.nan,876]}

In [ ]:
df=pd.DataFrame(dataset)

In [ ]:
sum(df.isnull().sum())

4

In [ ]:
#df["Marks"].fillna(df["Marks"].mean(),inplace=True)

In [ ]:
df

  Students_name  Marks  Attendance
0             A   65.0        90.0
1             B   54.0         NaN
2             C    NaN        85.0
3             D   66.0       120.0
4             E    NaN         NaN
5             F   78.0       876.0

In [ ]:
#df["Attendance"].fillna(df["Attendance"].mean(),inplace=True)

In [ ]:
df

  Students_name  Marks  Attendance
0             A   65.0        90.0
1             B   54.0         NaN
2             C    NaN        85.0
3             D   66.0       120.0
4             E    NaN         NaN
5             F   78.0       876.0

In [ ]:
df.loc[df["Attendance"]>100,"Attendance"]=100

In [ ]:
df

  Students_name  Marks  Attendance
0             A   65.0        90.0
1             B   54.0         NaN
2             C    NaN        85.0
3             D   66.0       100.0
4             E    NaN         NaN
5             F   78.0       100.0

In [ ]:
dataset = {"Students_name":["A","B","C","D","E"],
           "Marks":[50,60,70,80,90]}

In [ ]:
df=pd.DataFrame(dataset)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df["Marks"]=scaler.fit_transform(df[["Marks"]])

In [ ]:
df

  Students_name     Marks
0             A -1.414214
1             B -0.707107
2             C  0.000000
3             D  0.707107
4             E  1.414214